# Generated by Django 4.0.8 on 2023-01-15 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='actual_address',
            field=models.TextField(blank=True, help_text='Address of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(default=1, help_text='Age of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='ci_field',
            field=models.CharField(default='11111111111', max_length=11, validators=[django.core.validators.RegexValidator(message='CI must be conformed by eleven digits from 1 to 9', regex='^[0][1-9]\\d{9}$|^[1-9]\\d{9}$'), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='John', help_text='Name of User', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Doe', help_text='Last Name of User', max_length=255),
        ),
    ]
