# Generated by Django 4.0.8 on 2023-01-16 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_technology_technologyexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci_field',
            field=models.CharField(default='11111111111', max_length=11, validators=[django.core.validators.RegexValidator(message='CI must be conformed by eleven digits from 1 to 9', regex='\\d{11}'), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
